server:
  port: 8082

spring:
  application:
    name: typematch-api
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

pokedex:
  base-url: http://localhost:8081/api/pokemon